trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  inactiveColor: 'green'

stages:
- stage: Deploy
  jobs:
    - job: DeployStaticSite
      steps:
      - checkout: self
      
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'R_AzureSN' # Ensure this is the name of your Azure service connection
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group create --resource-group R_TRG --template-file main.bicep --parameters deploymentColor=$(inactiveColor)
      
      - task: AzureCLI@2
        inputs:
           azureSubscription: 'R_AzureSN'
           scriptType: 'bash'
           scriptLocation: 'inlineScript'
           inlineScript: |
              az storage blob upload-batch --source website/ --destination web --account-name storageAccountName
              
      - script: sleep 300
        displayName: 'Wait for 5 minutes for CDN to be available'

      - pwsh: |
           Install-Module -Name Pester -Force -Scope CurrentUser -AllowClobber
           Invoke-Pester -Script ./ptests.ps1
        displayName: 'Run Pester Tests'
    
